### ISSUE TITLE
Need variability in resource endpoints

### ISSUE THREAD

**Issue by saldoukhov** [wso2/charon#111] opened 2018-06-22 21:21 UTC
**Description:**
endpointURLMap is a static field on AbstractResourceManager. This makes impossible to properly process requests if the server publishes multiple SCIM endpoints, f.e.
localhost/scim/v2/companyA/Users and
localhost/scim/v2/companyB/Users
where each request is performed in a "company" context

**Suggested Labels:**
resources,url

**Affected Product Version:**
3.0.15

**Steps to reproduce:**
Try to implement UserManager in a way where requests for companies A and B are processed in isolation from each other.

**Comment by GDRDABARERA** [comment] 2018-07-20 10:55
In WSO2 IS, with the use of current implementation we can call multiple SCIM endpoints without any issue.
When you have multiple tenants like abc.com and wso2.com, the SCIM endpoints will be as follows,
- localhost/t/abc.com/scim/v2/Users
- localhost/t/wso2.com/scim/v2/Users

When the request comes to the IS, the TenantContextRewriteValve will get the tenant domain from the URL and set the tenant domain to the context. So we should not need to pass the context via the endpoint URL.

So we think this fix you have done is really not necessary at this core level. Please let us know your exact requirement so that we can help you with that.

Hence, resolving this as not a bug.

**Comment by GDRDABARERA** [comment] 2018-07-20 11:00
Please let us know your update. So that we can close this issue.

**Comment by saldoukhov** [comment] 2018-07-21 07:36
What if I don't want multiple tenants but I want to use path to isolate directories? F.e. our company is a service provider with a single domain but we allow multiple users to integrate their directories.
Anyway, you can close this issue, since we stopped our attempts to use charon due to other defects.

**Comment by GDRDABARERA** [comment] 2018-07-23 04:15
Closing the issue as they don't want this use-case and we don't have such use-case for the current implementation.

**Closed by GDRDABARERA** 2018-07-23 04:15 UTC
Labels: question
